name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential zlib1g-dev libzip-dev

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON

    - name: Build with Make
      run: |
        cd build
        make

    - name: Run Tests (if any)
      run: |
        cd build
        ctest --output-on-failure
      if: success() # Only run if the build step succeeds
